server:
  port: 8803


dubbo:
  application:
    name: user-service-edge  # 应用名称
    owner: hepan      # 应用所属者
    organization: hepan   # 应用所属组织
  registry:
    id: zookeeper-registry #注册中心id
    protocol: zookeeper    #注册中心协议
    address: zookeeper://127.0.0.1:2181 #注册中心地址
  protocol:
    name: dubbo   #协议名称
    port: 20882   #协议端口
    accesslog: dubbo-access.log #协议访问log

#redis config
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30000