
dubbo:
  application:
    id: message-service
    name: message-service  #应用名称
    owner: hepan      #应用所属者
    organization: hepan   #应用所属组织
  registry:
    id: zookeeper-registry #注册中心id
    protocol: zookeeper    #注册中心协议
    address: zookeeper://127.0.0.1:2181 #注册中心地址
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo   #协议名称
    port: 20883   #协议端口
    accesslog: dubbo-access.log #协议访问log
  provider:
    retries: 0    #重试次数
    timeout: 3000 #超时时间
  monitor:
    protocol: registry # 注册监控中心